const file=document.querySelector('#file'),canvas=document.querySelector('#canvas'),ctx=canvas.getContext('2d'),stage=document.querySelector('#stage'),empty=document.querySelector('.empty'),list=document.querySelector('#items'),classes=document.querySelector('#classes'),label=document.querySelector('#label');let img=new Image(),boxes=[],start=null,src='';
function refreshClasses(){label.innerHTML='';classes.value.split(',').map(x=>x.trim()).filter(Boolean).forEach(x=>label.add(new Option(x,x)))}classes.oninput=refreshClasses;refreshClasses();
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);if(img.src)ctx.drawImage(img,0,0);boxes.forEach((b,i)=>{ctx.strokeStyle='#7ee787';ctx.lineWidth=Math.max(2,canvas.width/500);ctx.strokeRect(b.x,b.y,b.w,b.h);ctx.fillStyle='#7ee787';ctx.font='14px system-ui';ctx.fillText(`${i+1} � ${b.label}`,b.x+4,Math.max(16,b.y-5))});list.innerHTML=boxes.map((b,i)=>`<li>${b.label} � [${Math.round(b.x)}, ${Math.round(b.y)}, ${Math.round(b.w)}, ${Math.round(b.h)}] <button data-i="${i}">Delete</button></li>`).join('');list.querySelectorAll('button').forEach(x=>x.onclick=()=>{boxes.splice(+x.dataset.i,1);draw()})}
file.onchange=()=>{const f=file.files[0];if(!f)return;src=f.name;img.onload=()=>{canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;empty.hidden=true;draw()};img.src=URL.createObjectURL(f)};
canvas.onpointerdown=e=>{if(!img.src)return;const r=canvas.getBoundingClientRect(),sx=canvas.width/r.width,sy=canvas.height/r.height;start={x:(e.clientX-r.left)*sx,y:(e.clientY-r.top)*sy}};
canvas.onpointerup=e=>{if(!start)return;const r=canvas.getBoundingClientRect(),sx=canvas.width/r.width,sy=canvas.height/r.height,x=(e.clientX-r.left)*sx,y=(e.clientY-r.top)*sy,b={x:Math.min(x,start.x),y:Math.min(y,start.y),w:Math.abs(x-start.x),h:Math.abs(y-start.y),label:label.value};if(b.w>3&&b.h>3&&b.label)boxes.push(b);start=null;draw()};
document.querySelector('#undo').onclick=()=>{boxes.pop();draw()};document.querySelector('#clear').onclick=()=>{boxes=[];draw()};
function download(name,data,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#yolo').onclick=()=>{const names=classes.value.split(',').map(x=>x.trim()).filter(Boolean),txt=boxes.map(b=>`${names.indexOf(b.label)} ${((b.x+b.w/2)/canvas.width).toFixed(6)} ${((b.y+b.h/2)/canvas.height).toFixed(6)} ${(b.w/canvas.width).toFixed(6)} ${(b.h/canvas.height).toFixed(6)}`).join('\n');download('labels.txt',txt,'text/plain');download('classes.txt',names.join('\n'),'text/plain')};
document.querySelector('#coco').onclick=()=>download('annotations.json',JSON.stringify({images:[{id:1,file_name:src,width:canvas.width,height:canvas.height}],categories:classes.value.split(',').map((name,id)=>({id:id+1,name:name.trim()})),annotations:boxes.map((b,id)=>({id:id+1,image_id:1,category_id:classes.value.split(',').map(x=>x.trim()).indexOf(b.label)+1,bbox:[b.x,b.y,b.w,b.h],area:b.w*b.h,iscrowd:0}))},null,2),'application/json');